
  
  export interface User {
    id: string
    name: string
    email: string
    role: string
    status: string
    joinDate: string
    avatar: string
  }
  
  export interface Product {
    id: string
    name: string
    category: string
    price: number
    priceFormatted: string
    stock: number
    sku: string
    status: string
    image: string
  }
  
  export interface Shop {
    id: string
    name: string
    owner: string
    location: string
    revenue: number
    revenueFormatted: string
    status: string
    rating: number
    products: number
  }
  
  export interface Company {
    id: string
    name: string
    industry: string
    employees: number
    revenue: number
    revenueFormatted: string
    country: string
    status: string
    founded: number
  }
  
  export interface Country {
    id: string
    name: string
    code: string
    capital: string
    population: number
    populationFormatted: string
    currency: string
    region: string
    flag: string
  }
  
  
  export const allCountries: Country[] = [
    {
      id: "AF",
      name: "Afghanistan",
      code: "AF",
      capital: "Kabul",
      population: 38928346,
      currency: "AFN",
      region: "Asia",
      flag: "🇦🇫",
    },
    {
      id: "AL",
      name: "Albania",
      code: "AL",
      capital: "Tirana",
      population: 2877797,
      currency: "ALL",
      region: "Europe",
      flag: "🇦🇱",
    },
    {
      id: "DZ",
      name: "Algeria",
      code: "DZ",
      capital: "Algiers",
      population: 43851044,
      currency: "DZD",
      region: "Africa",
      flag: "🇩🇿",
    },
    {
      id: "AD",
      name: "Andorra",
      code: "AD",
      capital: "Andorra la Vella",
      population: 77265,
      currency: "EUR",
      region: "Europe",
      flag: "🇦🇩",
    },
    {
      id: "AO",
      name: "Angola",
      code: "AO",
      capital: "Luanda",
      population: 32866272,
      currency: "AOA",
      region: "Africa",
      flag: "🇦🇴",
    },
    {
      id: "AG",
      name: "Antigua and Barbuda",
      code: "AG",
      capital: "Saint John's",
      population: 97929,
      currency: "XCD",
      region: "Americas",
      flag: "🇦🇬",
    },
    {
      id: "AR",
      name: "Argentina",
      code: "AR",
      capital: "Buenos Aires",
      population: 45195774,
      currency: "ARS",
      region: "Americas",
      flag: "🇦🇷",
    },
    {
      id: "AM",
      name: "Armenia",
      code: "AM",
      capital: "Yerevan",
      population: 2963243,
      currency: "AMD",
      region: "Asia",
      flag: "🇦🇲",
    },
    {
      id: "AU",
      name: "Australia",
      code: "AU",
      capital: "Canberra",
      population: 25499884,
      currency: "AUD",
      region: "Oceania",
      flag: "🇦🇺",
    },
    {
      id: "AT",
      name: "Austria",
      code: "AT",
      capital: "Vienna",
      population: 9006398,
      currency: "EUR",
      region: "Europe",
      flag: "🇦🇹",
    },
    {
      id: "AZ",
      name: "Azerbaijan",
      code: "AZ",
      capital: "Baku",
      population: 10139177,
      currency: "AZN",
      region: "Asia",
      flag: "🇦🇿",
    },
    {
      id: "BS",
      name: "Bahamas",
      code: "BS",
      capital: "Nassau",
      population: 393244,
      currency: "BSD",
      region: "Americas",
      flag: "🇧🇸",
    },
    {
      id: "BH",
      name: "Bahrain",
      code: "BH",
      capital: "Manama",
      population: 1701575,
      currency: "BHD",
      region: "Asia",
      flag: "🇧🇭",
    },
    {
      id: "BD",
      name: "Bangladesh",
      code: "BD",
      capital: "Dhaka",
      population: 164689383,
      currency: "BDT",
      region: "Asia",
      flag: "🇧🇩",
    },
    {
      id: "BB",
      name: "Barbados",
      code: "BB",
      capital: "Bridgetown",
      population: 287375,
      currency: "BBD",
      region: "Americas",
      flag: "🇧🇧",
    },
    {
      id: "BY",
      name: "Belarus",
      code: "BY",
      capital: "Minsk",
      population: 9449323,
      currency: "BYN",
      region: "Europe",
      flag: "🇧🇾",
    },
    {
      id: "BE",
      name: "Belgium",
      code: "BE",
      capital: "Brussels",
      population: 11589623,
      currency: "EUR",
      region: "Europe",
      flag: "🇧🇪",
    },
    {
      id: "BZ",
      name: "Belize",
      code: "BZ",
      capital: "Belmopan",
      population: 397628,
      currency: "BZD",
      region: "Americas",
      flag: "🇧🇿",
    },
    {
      id: "BJ",
      name: "Benin",
      code: "BJ",
      capital: "Porto-Novo",
      population: 12123200,
      currency: "XOF",
      region: "Africa",
      flag: "🇧🇯",
    },
    {
      id: "BT",
      name: "Bhutan",
      code: "BT",
      capital: "Thimphu",
      population: 771608,
      currency: "BTN",
      region: "Asia",
      flag: "🇧🇹",
    },
    {
      id: "BO",
      name: "Bolivia",
      code: "BO",
      capital: "Sucre",
      population: 11673021,
      currency: "BOB",
      region: "Americas",
      flag: "🇧🇴",
    },
    {
      id: "BA",
      name: "Bosnia and Herzegovina",
      code: "BA",
      capital: "Sarajevo",
      population: 3280819,
      currency: "BAM",
      region: "Europe",
      flag: "🇧🇦",
    },
    {
      id: "BW",
      name: "Botswana",
      code: "BW",
      capital: "Gaborone",
      population: 2351627,
      currency: "BWP",
      region: "Africa",
      flag: "🇧🇼",
    },
    {
      id: "BR",
      name: "Brazil",
      code: "BR",
      capital: "Brasília",
      population: 212559417,
      currency: "BRL",
      region: "Americas",
      flag: "🇧🇷",
    },
    {
      id: "BN",
      name: "Brunei",
      code: "BN",
      capital: "Bandar Seri Begawan",
      population: 437479,
      currency: "BND",
      region: "Asia",
      flag: "🇧🇳",
    },
    {
      id: "BG",
      name: "Bulgaria",
      code: "BG",
      capital: "Sofia",
      population: 6948445,
      currency: "BGN",
      region: "Europe",
      flag: "🇧🇬",
    },
    {
      id: "BF",
      name: "Burkina Faso",
      code: "BF",
      capital: "Ouagadougou",
      population: 20903273,
      currency: "XOF",
      region: "Africa",
      flag: "🇧🇫",
    },
    {
      id: "BI",
      name: "Burundi",
      code: "BI",
      capital: "Gitega",
      population: 11890784,
      currency: "BIF",
      region: "Africa",
      flag: "🇧🇮",
    },
    {
      id: "CV",
      name: "Cabo Verde",
      code: "CV",
      capital: "Praia",
      population: 555987,
      currency: "CVE",
      region: "Africa",
      flag: "🇨🇻",
    },
    {
      id: "KH",
      name: "Cambodia",
      code: "KH",
      capital: "Phnom Penh",
      population: 16718965,
      currency: "KHR",
      region: "Asia",
      flag: "🇰🇭",
    },
    {
      id: "CM",
      name: "Cameroon",
      code: "CM",
      capital: "Yaoundé",
      population: 26545863,
      currency: "XAF",
      region: "Africa",
      flag: "🇨🇲",
    },
    {
      id: "CA",
      name: "Canada",
      code: "CA",
      capital: "Ottawa",
      population: 37742154,
      currency: "CAD",
      region: "Americas",
      flag: "🇨🇦",
    },
    {
      id: "CF",
      name: "Central African Republic",
      code: "CF",
      capital: "Bangui",
      population: 4829767,
      currency: "XAF",
      region: "Africa",
      flag: "🇨🇫",
    },
    {
      id: "TD",
      name: "Chad",
      code: "TD",
      capital: "N'Djamena",
      population: 16425864,
      currency: "XAF",
      region: "Africa",
      flag: "🇹🇩",
    },
    {
      id: "CL",
      name: "Chile",
      code: "CL",
      capital: "Santiago",
      population: 19116201,
      currency: "CLP",
      region: "Americas",
      flag: "🇨🇱",
    },
    {
      id: "CN",
      name: "China",
      code: "CN",
      capital: "Beijing",
      population: 1439323776,
      currency: "CNY",
      region: "Asia",
      flag: "🇨🇳",
    },
    {
      id: "CO",
      name: "Colombia",
      code: "CO",
      capital: "Bogotá",
      population: 50882891,
      currency: "COP",
      region: "Americas",
      flag: "🇨🇴",
    },
    {
      id: "KM",
      name: "Comoros",
      code: "KM",
      capital: "Moroni",
      population: 869601,
      currency: "KMF",
      region: "Africa",
      flag: "🇰🇲",
    },
    {
      id: "CG",
      name: "Congo",
      code: "CG",
      capital: "Brazzaville",
      population: 5518087,
      currency: "XAF",
      region: "Africa",
      flag: "🇨🇬",
    },
    {
      id: "CR",
      name: "Costa Rica",
      code: "CR",
      capital: "San José",
      population: 5094118,
      currency: "CRC",
      region: "Americas",
      flag: "🇨🇷",
    },
    {
      id: "HR",
      name: "Croatia",
      code: "HR",
      capital: "Zagreb",
      population: 4105267,
      currency: "EUR",
      region: "Europe",
      flag: "🇭🇷",
    },
    {
      id: "CU",
      name: "Cuba",
      code: "CU",
      capital: "Havana",
      population: 11326616,
      currency: "CUP",
      region: "Americas",
      flag: "🇨🇺",
    },
    {
      id: "CY",
      name: "Cyprus",
      code: "CY",
      capital: "Nicosia",
      population: 1207359,
      currency: "EUR",
      region: "Europe",
      flag: "🇨🇾",
    },
    {
      id: "CZ",
      name: "Czech Republic",
      code: "CZ",
      capital: "Prague",
      population: 10708981,
      currency: "CZK",
      region: "Europe",
      flag: "🇨🇿",
    },
    {
      id: "DK",
      name: "Denmark",
      code: "DK",
      capital: "Copenhagen",
      population: 5792202,
      currency: "DKK",
      region: "Europe",
      flag: "🇩🇰",
    },
    {
      id: "DJ",
      name: "Djibouti",
      code: "DJ",
      capital: "Djibouti",
      population: 988000,
      currency: "DJF",
      region: "Africa",
      flag: "🇩🇯",
    },
    {
      id: "DM",
      name: "Dominica",
      code: "DM",
      capital: "Roseau",
      population: 71986,
      currency: "XCD",
      region: "Americas",
      flag: "🇩🇲",
    },
    {
      id: "DO",
      name: "Dominican Republic",
      code: "DO",
      capital: "Santo Domingo",
      population: 10847910,
      currency: "DOP",
      region: "Americas",
      flag: "🇩🇴",
    },
    {
      id: "EC",
      name: "Ecuador",
      code: "EC",
      capital: "Quito",
      population: 17643054,
      currency: "USD",
      region: "Americas",
      flag: "🇪🇨",
    },
    {
      id: "EG",
      name: "Egypt",
      code: "EG",
      capital: "Cairo",
      population: 102334404,
      currency: "EGP",
      region: "Africa",
      flag: "🇪🇬",
    },
    {
      id: "SV",
      name: "El Salvador",
      code: "SV",
      capital: "San Salvador",
      population: 6486205,
      currency: "USD",
      region: "Americas",
      flag: "🇸🇻",
    },
    {
      id: "GQ",
      name: "Equatorial Guinea",
      code: "GQ",
      capital: "Malabo",
      population: 1402985,
      currency: "XAF",
      region: "Africa",
      flag: "🇬🇶",
    },
    {
      id: "ER",
      name: "Eritrea",
      code: "ER",
      capital: "Asmara",
      population: 3546421,
      currency: "ERN",
      region: "Africa",
      flag: "🇪🇷",
    },
    {
      id: "EE",
      name: "Estonia",
      code: "EE",
      capital: "Tallinn",
      population: 1326535,
      currency: "EUR",
      region: "Europe",
      flag: "🇪🇪",
    },
    {
      id: "SZ",
      name: "Eswatini",
      code: "SZ",
      capital: "Mbabane",
      population: 1160164,
      currency: "SZL",
      region: "Africa",
      flag: "🇸🇿",
    },
    {
      id: "ET",
      name: "Ethiopia",
      code: "ET",
      capital: "Addis Ababa",
      population: 114963588,
      currency: "ETB",
      region: "Africa",
      flag: "🇪🇹",
    },
    {
      id: "FJ",
      name: "Fiji",
      code: "FJ",
      capital: "Suva",
      population: 896445,
      currency: "FJD",
      region: "Oceania",
      flag: "🇫🇯",
    },
    {
      id: "FI",
      name: "Finland",
      code: "FI",
      capital: "Helsinki",
      population: 5540720,
      currency: "EUR",
      region: "Europe",
      flag: "🇫🇮",
    },
    {
      id: "FR",
      name: "France",
      code: "FR",
      capital: "Paris",
      population: 65273511,
      currency: "EUR",
      region: "Europe",
      flag: "🇫🇷",
    },
    {
      id: "GA",
      name: "Gabon",
      code: "GA",
      capital: "Libreville",
      population: 2225734,
      currency: "XAF",
      region: "Africa",
      flag: "🇬🇦",
    },
    {
      id: "GM",
      name: "Gambia",
      code: "GM",
      capital: "Banjul",
      population: 2416668,
      currency: "GMD",
      region: "Africa",
      flag: "🇬🇲",
    },
    {
      id: "GE",
      name: "Georgia",
      code: "GE",
      capital: "Tbilisi",
      population: 3989167,
      currency: "GEL",
      region: "Asia",
      flag: "🇬🇪",
    },
    {
      id: "DE",
      name: "Germany",
      code: "DE",
      capital: "Berlin",
      population: 83783942,
      currency: "EUR",
      region: "Europe",
      flag: "🇩🇪",
    },
    {
      id: "GH",
      name: "Ghana",
      code: "GH",
      capital: "Accra",
      population: 31072940,
      currency: "GHS",
      region: "Africa",
      flag: "🇬🇭",
    },
    {
      id: "GR",
      name: "Greece",
      code: "GR",
      capital: "Athens",
      population: 10423054,
      currency: "EUR",
      region: "Europe",
      flag: "🇬🇷",
    },
    {
      id: "GD",
      name: "Grenada",
      code: "GD",
      capital: "St. George's",
      population: 112523,
      currency: "XCD",
      region: "Americas",
      flag: "🇬🇩",
    },
    {
      id: "GT",
      name: "Guatemala",
      code: "GT",
      capital: "Guatemala City",
      population: 17915568,
      currency: "GTQ",
      region: "Americas",
      flag: "🇬🇹",
    },
    {
      id: "GN",
      name: "Guinea",
      code: "GN",
      capital: "Conakry",
      population: 13132795,
      currency: "GNF",
      region: "Africa",
      flag: "🇬🇳",
    },
    {
      id: "GW",
      name: "Guinea-Bissau",
      code: "GW",
      capital: "Bissau",
      population: 1968001,
      currency: "XOF",
      region: "Africa",
      flag: "🇬🇼",
    },
    {
      id: "GY",
      name: "Guyana",
      code: "GY",
      capital: "Georgetown",
      population: 786552,
      currency: "GYD",
      region: "Americas",
      flag: "🇬🇾",
    },
    {
      id: "HT",
      name: "Haiti",
      code: "HT",
      capital: "Port-au-Prince",
      population: 11402528,
      currency: "HTG",
      region: "Americas",
      flag: "🇭🇹",
    },
    {
      id: "HN",
      name: "Honduras",
      code: "HN",
      capital: "Tegucigalpa",
      population: 9904607,
      currency: "HNL",
      region: "Americas",
      flag: "🇭🇳",
    },
    {
      id: "HU",
      name: "Hungary",
      code: "HU",
      capital: "Budapest",
      population: 9660351,
      currency: "HUF",
      region: "Europe",
      flag: "🇭🇺",
    },
    {
      id: "IS",
      name: "Iceland",
      code: "IS",
      capital: "Reykjavik",
      population: 341243,
      currency: "ISK",
      region: "Europe",
      flag: "🇮🇸",
    },
    {
      id: "IN",
      name: "India",
      code: "IN",
      capital: "New Delhi",
      population: 1380004385,
      currency: "INR",
      region: "Asia",
      flag: "🇮🇳",
    },
    {
      id: "ID",
      name: "Indonesia",
      code: "ID",
      capital: "Jakarta",
      population: 273523615,
      currency: "IDR",
      region: "Asia",
      flag: "🇮🇩",
    },
    {
      id: "IR",
      name: "Iran",
      code: "IR",
      capital: "Tehran",
      population: 83992949,
      currency: "IRR",
      region: "Asia",
      flag: "🇮🇷",
    },
    {
      id: "IQ",
      name: "Iraq",
      code: "IQ",
      capital: "Baghdad",
      population: 40222493,
      currency: "IQD",
      region: "Asia",
      flag: "🇮🇶",
    },
    {
      id: "IE",
      name: "Ireland",
      code: "IE",
      capital: "Dublin",
      population: 4937786,
      currency: "EUR",
      region: "Europe",
      flag: "🇮🇪",
    },
    {
      id: "IL",
      name: "Israel",
      code: "IL",
      capital: "Jerusalem",
      population: 8655535,
      currency: "ILS",
      region: "Asia",
      flag: "🇮🇱",
    },
    {
      id: "IT",
      name: "Italy",
      code: "IT",
      capital: "Rome",
      population: 60461826,
      currency: "EUR",
      region: "Europe",
      flag: "🇮🇹",
    },
    {
      id: "JM",
      name: "Jamaica",
      code: "JM",
      capital: "Kingston",
      population: 2961167,
      currency: "JMD",
      region: "Americas",
      flag: "🇯🇲",
    },
    {
      id: "JP",
      name: "Japan",
      code: "JP",
      capital: "Tokyo",
      population: 126476461,
      currency: "JPY",
      region: "Asia",
      flag: "🇯🇵",
    },
    {
      id: "JO",
      name: "Jordan",
      code: "JO",
      capital: "Amman",
      population: 10203134,
      currency: "JOD",
      region: "Asia",
      flag: "🇯🇴",
    },
    {
      id: "KZ",
      name: "Kazakhstan",
      code: "KZ",
      capital: "Nur-Sultan",
      population: 18776707,
      currency: "KZT",
      region: "Asia",
      flag: "🇰🇿",
    },
    {
      id: "KE",
      name: "Kenya",
      code: "KE",
      capital: "Nairobi",
      population: 53771296,
      currency: "KES",
      region: "Africa",
      flag: "🇰🇪",
    },
    {
      id: "KI",
      name: "Kiribati",
      code: "KI",
      capital: "Tarawa",
      population: 119449,
      currency: "AUD",
      region: "Oceania",
      flag: "🇰🇮",
    },
    {
      id: "KP",
      name: "North Korea",
      code: "KP",
      capital: "Pyongyang",
      population: 25778816,
      currency: "KPW",
      region: "Asia",
      flag: "🇰🇵",
    },
    {
      id: "KR",
      name: "South Korea",
      code: "KR",
      capital: "Seoul",
      population: 51269185,
      currency: "KRW",
      region: "Asia",
      flag: "🇰🇷",
    },
    {
      id: "KW",
      name: "Kuwait",
      code: "KW",
      capital: "Kuwait City",
      population: 4270571,
      currency: "KWD",
      region: "Asia",
      flag: "🇰🇼",
    },
    {
      id: "KG",
      name: "Kyrgyzstan",
      code: "KG",
      capital: "Bishkek",
      population: 6524195,
      currency: "KGS",
      region: "Asia",
      flag: "🇰🇬",
    },
    {
      id: "LA",
      name: "Laos",
      code: "LA",
      capital: "Vientiane",
      population: 7275560,
      currency: "LAK",
      region: "Asia",
      flag: "🇱🇦",
    },
    {
      id: "LV",
      name: "Latvia",
      code: "LV",
      capital: "Riga",
      population: 1886198,
      currency: "EUR",
      region: "Europe",
      flag: "🇱🇻",
    },
    {
      id: "LB",
      name: "Lebanon",
      code: "LB",
      capital: "Beirut",
      population: 6825445,
      currency: "LBP",
      region: "Asia",
      flag: "🇱🇧",
    },
    {
      id: "LS",
      name: "Lesotho",
      code: "LS",
      capital: "Maseru",
      population: 2142249,
      currency: "LSL",
      region: "Africa",
      flag: "🇱🇸",
    },
    {
      id: "LR",
      name: "Liberia",
      code: "LR",
      capital: "Monrovia",
      population: 5057681,
      currency: "LRD",
      region: "Africa",
      flag: "🇱🇷",
    },
    {
      id: "LY",
      name: "Libya",
      code: "LY",
      capital: "Tripoli",
      population: 6871292,
      currency: "LYD",
      region: "Africa",
      flag: "🇱🇾",
    },
    {
      id: "LI",
      name: "Liechtenstein",
      code: "LI",
      capital: "Vaduz",
      population: 38128,
      currency: "CHF",
      region: "Europe",
      flag: "🇱🇮",
    },
    {
      id: "LT",
      name: "Lithuania",
      code: "LT",
      capital: "Vilnius",
      population: 2722289,
      currency: "EUR",
      region: "Europe",
      flag: "🇱🇹",
    },
    {
      id: "LU",
      name: "Luxembourg",
      code: "LU",
      capital: "Luxembourg",
      population: 625978,
      currency: "EUR",
      region: "Europe",
      flag: "🇱🇺",
    },
    {
      id: "MG",
      name: "Madagascar",
      code: "MG",
      capital: "Antananarivo",
      population: 27691018,
      currency: "MGA",
      region: "Africa",
      flag: "🇲🇬",
    },
    {
      id: "MW",
      name: "Malawi",
      code: "MW",
      capital: "Lilongwe",
      population: 19129952,
      currency: "MWK",
      region: "Africa",
      flag: "🇲🇼",
    },
    {
      id: "MY",
      name: "Malaysia",
      code: "MY",
      capital: "Kuala Lumpur",
      population: 32365999,
      currency: "MYR",
      region: "Asia",
      flag: "🇲🇾",
    },
    {
      id: "MV",
      name: "Maldives",
      code: "MV",
      capital: "Malé",
      population: 540544,
      currency: "MVR",
      region: "Asia",
      flag: "🇲🇻",
    },
    {
      id: "ML",
      name: "Mali",
      code: "ML",
      capital: "Bamako",
      population: 20250833,
      currency: "XOF",
      region: "Africa",
      flag: "🇲🇱",
    },
    {
      id: "MT",
      name: "Malta",
      code: "MT",
      capital: "Valletta",
      population: 441543,
      currency: "EUR",
      region: "Europe",
      flag: "🇲🇹",
    },
    {
      id: "MH",
      name: "Marshall Islands",
      code: "MH",
      capital: "Majuro",
      population: 59190,
      currency: "USD",
      region: "Oceania",
      flag: "🇲🇭",
    },
    {
      id: "MR",
      name: "Mauritania",
      code: "MR",
      capital: "Nouakchott",
      population: 4649658,
      currency: "MRU",
      region: "Africa",
      flag: "🇲🇷",
    },
    {
      id: "MU",
      name: "Mauritius",
      code: "MU",
      capital: "Port Louis",
      population: 1271768,
      currency: "MUR",
      region: "Africa",
      flag: "🇲🇺",
    },
    {
      id: "MX",
      name: "Mexico",
      code: "MX",
      capital: "Mexico City",
      population: 128932753,
      currency: "MXN",
      region: "Americas",
      flag: "🇲🇽",
    },
    {
      id: "FM",
      name: "Micronesia",
      code: "FM",
      capital: "Palikir",
      population: 115023,
      currency: "USD",
      region: "Oceania",
      flag: "🇫🇲",
    },
    {
      id: "MD",
      name: "Moldova",
      code: "MD",
      capital: "Chișinău",
      population: 4033963,
      currency: "MDL",
      region: "Europe",
      flag: "🇲🇩",
    },
    {
      id: "MC",
      name: "Monaco",
      code: "MC",
      capital: "Monaco",
      population: 39242,
      currency: "EUR",
      region: "Europe",
      flag: "🇲🇨",
    },
    {
      id: "MN",
      name: "Mongolia",
      code: "MN",
      capital: "Ulaanbaatar",
      population: 3278290,
      currency: "MNT",
      region: "Asia",
      flag: "🇲🇳",
    },
    {
      id: "ME",
      name: "Montenegro",
      code: "ME",
      capital: "Podgorica",
      population: 628066,
      currency: "EUR",
      region: "Europe",
      flag: "🇲🇪",
    },
    {
      id: "MA",
      name: "Morocco",
      code: "MA",
      capital: "Rabat",
      population: 36910560,
      currency: "MAD",
      region: "Africa",
      flag: "🇲🇦",
    },
    {
      id: "MZ",
      name: "Mozambique",
      code: "MZ",
      capital: "Maputo",
      population: 31255435,
      currency: "MZN",
      region: "Africa",
      flag: "🇲🇿",
    },
    {
      id: "MM",
      name: "Myanmar",
      code: "MM",
      capital: "Naypyidaw",
      population: 54409800,
      currency: "MMK",
      region: "Asia",
      flag: "🇲🇲",
    },
    {
      id: "NA",
      name: "Namibia",
      code: "NA",
      capital: "Windhoek",
      population: 2540905,
      currency: "NAD",
      region: "Africa",
      flag: "🇳🇦",
    },
    {
      id: "NR",
      name: "Nauru",
      code: "NR",
      capital: "Yaren",
      population: 10824,
      currency: "AUD",
      region: "Oceania",
      flag: "🇳🇷",
    },
    {
      id: "NP",
      name: "Nepal",
      code: "NP",
      capital: "Kathmandu",
      population: 29136808,
      currency: "NPR",
      region: "Asia",
      flag: "🇳🇵",
    },
    {
      id: "NL",
      name: "Netherlands",
      code: "NL",
      capital: "Amsterdam",
      population: 17134872,
      currency: "EUR",
      region: "Europe",
      flag: "🇳🇱",
    },
    {
      id: "NZ",
      name: "New Zealand",
      code: "NZ",
      capital: "Wellington",
      population: 4822233,
      currency: "NZD",
      region: "Oceania",
      flag: "🇳🇿",
    },
    {
      id: "NI",
      name: "Nicaragua",
      code: "NI",
      capital: "Managua",
      population: 6624554,
      currency: "NIO",
      region: "Americas",
      flag: "🇳🇮",
    },
    {
      id: "NE",
      name: "Niger",
      code: "NE",
      capital: "Niamey",
      population: 24206644,
      currency: "XOF",
      region: "Africa",
      flag: "🇳🇪",
    },
    {
      id: "NG",
      name: "Nigeria",
      code: "NG",
      capital: "Abuja",
      population: 206139589,
      currency: "NGN",
      region: "Africa",
      flag: "🇳🇬",
    },
    {
      id: "MK",
      name: "North Macedonia",
      code: "MK",
      capital: "Skopje",
      population: 2083374,
      currency: "MKD",
      region: "Europe",
      flag: "🇲🇰",
    },
    {
      id: "NO",
      name: "Norway",
      code: "NO",
      capital: "Oslo",
      population: 5421241,
      currency: "NOK",
      region: "Europe",
      flag: "🇳🇴",
    },
    {
      id: "OM",
      name: "Oman",
      code: "OM",
      capital: "Muscat",
      population: 5106626,
      currency: "OMR",
      region: "Asia",
      flag: "🇴🇲",
    },
    {
      id: "PK",
      name: "Pakistan",
      code: "PK",
      capital: "Islamabad",
      population: 220892340,
      currency: "PKR",
      region: "Asia",
      flag: "🇵🇰",
    },
    {
      id: "PW",
      name: "Palau",
      code: "PW",
      capital: "Ngerulmud",
      population: 18094,
      currency: "USD",
      region: "Oceania",
      flag: "🇵🇼",
    },
    {
      id: "PA",
      name: "Panama",
      code: "PA",
      capital: "Panama City",
      population: 4314767,
      currency: "PAB",
      region: "Americas",
      flag: "🇵🇦",
    },
    {
      id: "PG",
      name: "Papua New Guinea",
      code: "PG",
      capital: "Port Moresby",
      population: 8947024,
      currency: "PGK",
      region: "Oceania",
      flag: "🇵🇬",
    },
    {
      id: "PY",
      name: "Paraguay",
      code: "PY",
      capital: "Asunción",
      population: 7132538,
      currency: "PYG",
      region: "Americas",
      flag: "🇵🇾",
    },
    {
      id: "PE",
      name: "Peru",
      code: "PE",
      capital: "Lima",
      population: 32971854,
      currency: "PEN",
      region: "Americas",
      flag: "🇵🇪",
    },
    {
      id: "PH",
      name: "Philippines",
      code: "PH",
      capital: "Manila",
      population: 109581078,
      currency: "PHP",
      region: "Asia",
      flag: "🇵🇭",
    },
    {
      id: "PL",
      name: "Poland",
      code: "PL",
      capital: "Warsaw",
      population: 37846611,
      currency: "PLN",
      region: "Europe",
      flag: "🇵🇱",
    },
    {
      id: "PT",
      name: "Portugal",
      code: "PT",
      capital: "Lisbon",
      population: 10196709,
      currency: "EUR",
      region: "Europe",
      flag: "🇵🇹",
    },
    {
      id: "QA",
      name: "Qatar",
      code: "QA",
      capital: "Doha",
      population: 2881053,
      currency: "QAR",
      region: "Asia",
      flag: "🇶🇦",
    },
    {
      id: "RO",
      name: "Romania",
      code: "RO",
      capital: "Bucharest",
      population: 19237691,
      currency: "RON",
      region: "Europe",
      flag: "🇷🇴",
    },
    {
      id: "RU",
      name: "Russia",
      code: "RU",
      capital: "Moscow",
      population: 145934462,
      currency: "RUB",
      region: "Europe",
      flag: "🇷🇺",
    },
    {
      id: "RW",
      name: "Rwanda",
      code: "RW",
      capital: "Kigali",
      population: 12952218,
      currency: "RWF",
      region: "Africa",
      flag: "🇷🇼",
    },
    {
      id: "KN",
      name: "Saint Kitts and Nevis",
      code: "KN",
      capital: "Basseterre",
      population: 53199,
      currency: "XCD",
      region: "Americas",
      flag: "🇰🇳",
    },
    {
      id: "LC",
      name: "Saint Lucia",
      code: "LC",
      capital: "Castries",
      population: 183627,
      currency: "XCD",
      region: "Americas",
      flag: "🇱🇨",
    },
    {
      id: "VC",
      name: "Saint Vincent and the Grenadines",
      code: "VC",
      capital: "Kingstown",
      population: 110940,
      currency: "XCD",
      region: "Americas",
      flag: "🇻🇨",
    },
    {
      id: "WS",
      name: "Samoa",
      code: "WS",
      capital: "Apia",
      population: 198414,
      currency: "WST",
      region: "Oceania",
      flag: "🇼🇸",
    },
    {
      id: "SM",
      name: "San Marino",
      code: "SM",
      capital: "San Marino",
      population: 33931,
      currency: "EUR",
      region: "Europe",
      flag: "🇸🇲",
    },
    {
      id: "ST",
      name: "São Tomé and Príncipe",
      code: "ST",
      capital: "São Tomé",
      population: 219159,
      currency: "STN",
      region: "Africa",
      flag: "🇸🇹",
    },
    {
      id: "SA",
      name: "Saudi Arabia",
      code: "SA",
      capital: "Riyadh",
      population: 34813871,
      currency: "SAR",
      region: "Asia",
      flag: "🇸🇦",
    },
    {
      id: "SN",
      name: "Senegal",
      code: "SN",
      capital: "Dakar",
      population: 16743927,
      currency: "XOF",
      region: "Africa",
      flag: "🇸🇳",
    },
    {
      id: "RS",
      name: "Serbia",
      code: "RS",
      capital: "Belgrade",
      population: 8737371,
      currency: "RSD",
      region: "Europe",
      flag: "🇷🇸",
    },
    {
      id: "SC",
      name: "Seychelles",
      code: "SC",
      capital: "Victoria",
      population: 98347,
      currency: "SCR",
      region: "Africa",
      flag: "🇸🇨",
    },
    {
      id: "SL",
      name: "Sierra Leone",
      code: "SL",
      capital: "Freetown",
      population: 7976983,
      currency: "SLL",
      region: "Africa",
      flag: "🇸🇱",
    },
    {
      id: "SG",
      name: "Singapore",
      code: "SG",
      capital: "Singapore",
      population: 5850342,
      currency: "SGD",
      region: "Asia",
      flag: "🇸🇬",
    },
    {
      id: "SK",
      name: "Slovakia",
      code: "SK",
      capital: "Bratislava",
      population: 5459642,
      currency: "EUR",
      region: "Europe",
      flag: "🇸🇰",
    },
    {
      id: "SI",
      name: "Slovenia",
      code: "SI",
      capital: "Ljubljana",
      population: 2078938,
      currency: "EUR",
      region: "Europe",
      flag: "🇸🇮",
    },
    {
      id: "SB",
      name: "Solomon Islands",
      code: "SB",
      capital: "Honiara",
      population: 686884,
      currency: "SBD",
      region: "Oceania",
      flag: "🇸🇧",
    },
    {
      id: "SO",
      name: "Somalia",
      code: "SO",
      capital: "Mogadishu",
      population: 15893222,
      currency: "SOS",
      region: "Africa",
      flag: "🇸🇴",
    },
    {
      id: "ZA",
      name: "South Africa",
      code: "ZA",
      capital: "Pretoria",
      population: 59308690,
      currency: "ZAR",
      region: "Africa",
      flag: "🇿🇦",
    },
    {
      id: "SS",
      name: "South Sudan",
      code: "SS",
      capital: "Juba",
      population: 11193725,
      currency: "SSP",
      region: "Africa",
      flag: "🇸🇸",
    },
    {
      id: "ES",
      name: "Spain",
      code: "ES",
      capital: "Madrid",
      population: 46754778,
      currency: "EUR",
      region: "Europe",
      flag: "🇪🇸",
    },
    {
      id: "LK",
      name: "Sri Lanka",
      code: "LK",
      capital: "Colombo",
      population: 21413249,
      currency: "LKR",
      region: "Asia",
      flag: "🇱🇰",
    },
    {
      id: "SD",
      name: "Sudan",
      code: "SD",
      capital: "Khartoum",
      population: 43849260,
      currency: "SDG",
      region: "Africa",
      flag: "🇸🇩",
    },
    {
      id: "SR",
      name: "Suriname",
      code: "SR",
      capital: "Paramaribo",
      population: 586632,
      currency: "SRD",
      region: "Americas",
      flag: "🇸🇷",
    },
    {
      id: "SE",
      name: "Sweden",
      code: "SE",
      capital: "Stockholm",
      population: 10099265,
      currency: "SEK",
      region: "Europe",
      flag: "🇸🇪",
    },
    {
      id: "CH",
      name: "Switzerland",
      code: "CH",
      capital: "Bern",
      population: 8654622,
      currency: "CHF",
      region: "Europe",
      flag: "🇨🇭",
    },
    {
      id: "SY",
      name: "Syria",
      code: "SY",
      capital: "Damascus",
      population: 17500658,
      currency: "SYP",
      region: "Asia",
      flag: "🇸🇾",
    },
    {
      id: "TW",
      name: "Taiwan",
      code: "TW",
      capital: "Taipei",
      population: 23816775,
      currency: "TWD",
      region: "Asia",
      flag: "🇹🇼",
    },
    {
      id: "TJ",
      name: "Tajikistan",
      code: "TJ",
      capital: "Dushanbe",
      population: 9537645,
      currency: "TJS",
      region: "Asia",
      flag: "🇹🇯",
    },
    {
      id: "TZ",
      name: "Tanzania",
      code: "TZ",
      capital: "Dodoma",
      population: 59734218,
      currency: "TZS",
      region: "Africa",
      flag: "🇹🇿",
    },
    {
      id: "TH",
      name: "Thailand",
      code: "TH",
      capital: "Bangkok",
      population: 69799978,
      currency: "THB",
      region: "Asia",
      flag: "🇹🇭",
    },
    {
      id: "TL",
      name: "Timor-Leste",
      code: "TL",
      capital: "Dili",
      population: 1318445,
      currency: "USD",
      region: "Asia",
      flag: "🇹🇱",
    },
    {
      id: "TG",
      name: "Togo",
      code: "TG",
      capital: "Lomé",
      population: 8278724,
      currency: "XOF",
      region: "Africa",
      flag: "🇹🇬",
    },
    {
      id: "TO",
      name: "Tonga",
      code: "TO",
      capital: "Nuku'alofa",
      population: 105695,
      currency: "TOP",
      region: "Oceania",
      flag: "🇹🇴",
    },
    {
      id: "TT",
      name: "Trinidad and Tobago",
      code: "TT",
      capital: "Port of Spain",
      population: 1399488,
      currency: "TTD",
      region: "Americas",
      flag: "🇹🇹",
    },
    {
      id: "TN",
      name: "Tunisia",
      code: "TN",
      capital: "Tunis",
      population: 11818619,
      currency: "TND",
      region: "Africa",
      flag: "🇹🇳",
    },
    {
      id: "TR",
      name: "Turkey",
      code: "TR",
      capital: "Ankara",
      population: 84339067,
      currency: "TRY",
      region: "Asia",
      flag: "🇹🇷",
    },
    {
      id: "TM",
      name: "Turkmenistan",
      code: "TM",
      capital: "Ashgabat",
      population: 6031200,
      currency: "TMT",
      region: "Asia",
      flag: "🇹🇲",
    },
    {
      id: "TV",
      name: "Tuvalu",
      code: "TV",
      capital: "Funafuti",
      population: 11792,
      currency: "AUD",
      region: "Oceania",
      flag: "🇹🇻",
    },
    {
      id: "UG",
      name: "Uganda",
      code: "UG",
      capital: "Kampala",
      population: 45741007,
      currency: "UGX",
      region: "Africa",
      flag: "🇺🇬",
    },
    {
      id: "UA",
      name: "Ukraine",
      code: "UA",
      capital: "Kyiv",
      population: 43733762,
      currency: "UAH",
      region: "Europe",
      flag: "🇺🇦",
    },
    {
      id: "AE",
      name: "United Arab Emirates",
      code: "AE",
      capital: "Abu Dhabi",
      population: 9890402,
      currency: "AED",
      region: "Asia",
      flag: "🇦🇪",
    },
    {
      id: "GB",
      name: "United Kingdom",
      code: "GB",
      capital: "London",
      population: 67886011,
      currency: "GBP",
      region: "Europe",
      flag: "🇬🇧",
    },
    {
      id: "US",
      name: "United States",
      code: "US",
      capital: "Washington, D.C.",
      population: 331002651,
      currency: "USD",
      region: "Americas",
      flag: "🇺🇸",
    },
    {
      id: "UY",
      name: "Uruguay",
      code: "UY",
      capital: "Montevideo",
      population: 3473730,
      currency: "UYU",
      region: "Americas",
      flag: "🇺🇾",
    },
    {
      id: "UZ",
      name: "Uzbekistan",
      code: "UZ",
      capital: "Tashkent",
      population: 33469203,
      currency: "UZS",
      region: "Asia",
      flag: "🇺🇿",
    },
    {
      id: "VU",
      name: "Vanuatu",
      code: "VU",
      capital: "Port Vila",
      population: 307145,
      currency: "VUV",
      region: "Oceania",
      flag: "🇻🇺",
    },
    {
      id: "VA",
      name: "Vatican City",
      code: "VA",
      capital: "Vatican City",
      population: 801,
      currency: "EUR",
      region: "Europe",
      flag: "🇻🇦",
    },
    {
      id: "VE",
      name: "Venezuela",
      code: "VE",
      capital: "Caracas",
      population: 28435940,
      currency: "VES",
      region: "Americas",
      flag: "🇻🇪",
    },
    {
      id: "VN",
      name: "Vietnam",
      code: "VN",
      capital: "Hanoi",
      population: 97338579,
      currency: "VND",
      region: "Asia",
      flag: "🇻🇳",
    },
    {
      id: "YE",
      name: "Yemen",
      code: "YE",
      capital: "Sana'a",
      population: 29825964,
      currency: "YER",
      region: "Asia",
      flag: "🇾🇪",
    },
    {
      id: "ZM",
      name: "Zambia",
      code: "ZM",
      capital: "Lusaka",
      population: 18383955,
      currency: "ZMW",
      region: "Africa",
      flag: "🇿🇲",
    },
    {
      id: "ZW",
      name: "Zimbabwe",
      code: "ZW",
      capital: "Harare",
      population: 14862924,
      currency: "ZWL",
      region: "Africa",
      flag: "🇿🇼",
    },
  ].map((c) => ({
    ...c,
    populationFormatted: new Intl.NumberFormat("en-US").format(c.population),
  }))
  
  export function getDashboardStats() {
    return {
      totalUsers: 12847,
      totalRevenue: 2456789,
      activeShops: 342,
      totalProducts: 8567,
      userGrowth: 12.5,
      revenueGrowth: 8.3,
      shopGrowth: 5.2,
      productGrowth: -2.1,
    }
  }
  
  export function getRecentActivity() {
    return [
      { id: 1, action: "New user registered", user: "John Smith", time: "2 minutes ago", type: "user" },
      { id: 2, action: "Product added", user: "Sarah Johnson", time: "5 minutes ago", type: "product" },
      { id: 3, action: "Order completed", user: "Mike Davis", time: "12 minutes ago", type: "order" },
      { id: 4, action: "Shop approved", user: "Admin", time: "25 minutes ago", type: "shop" },
      { id: 5, action: "Payment received", user: "System", time: "1 hour ago", type: "payment" },
      { id: 6, action: "New review posted", user: "Emily Brown", time: "2 hours ago", type: "review" },
      { id: 7, action: "User deactivated", user: "Admin", time: "3 hours ago", type: "user" },
      { id: 8, action: "Product updated", user: "James Wilson", time: "4 hours ago", type: "product" },
    ]
  }
  
  export function getRevenueChartData() {
    return [
      { month: "Jan", revenue: 186000, orders: 1200 },
      { month: "Feb", revenue: 205000, orders: 1350 },
      { month: "Mar", revenue: 237000, orders: 1500 },
      { month: "Apr", revenue: 273000, orders: 1680 },
      { month: "May", revenue: 209000, orders: 1420 },
      { month: "Jun", revenue: 314000, orders: 1890 },
      { month: "Jul", revenue: 298000, orders: 1780 },
      { month: "Aug", revenue: 342000, orders: 2100 },
      { month: "Sep", revenue: 289000, orders: 1750 },
      { month: "Oct", revenue: 378000, orders: 2300 },
      { month: "Nov", revenue: 421000, orders: 2580 },
      { month: "Dec", revenue: 456000, orders: 2890 },
    ]
  }
  
  export function getUsersByRoleData() {
    return [
      { role: "Users", count: 8540, fill: "var(--color-chart-1)" },
      { role: "Editors", count: 2340, fill: "var(--color-chart-2)" },
      { role: "Moderators", count: 1250, fill: "var(--color-chart-3)" },
      { role: "Admins", count: 420, fill: "var(--color-chart-4)" },
      { role: "Developers", count: 297, fill: "var(--color-chart-5)" },
    ]
  }
  
  export function getTopProducts() {
    return [
      { id: 1, name: "Premium Widget Pro", sales: 2340, revenue: 46800 },
      { id: 2, name: "Ultra Gadget X", sales: 1890, revenue: 37800 },
      { id: 3, name: "Essential Kit Plus", sales: 1650, revenue: 33000 },
      { id: 4, name: "Modern Device 2.0", sales: 1420, revenue: 28400 },
      { id: 5, name: "Classic Tool Set", sales: 1180, revenue: 23600 },
    ]
  }
  